# Generated by Django 4.2.6 on 2023-11-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0002_remove_userinformation_chosen_farm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='category',
            field=models.CharField(default='management', max_length=128),
        ),
    ]
